query GetUser($userId: String!) {
  user(id: $userId) {
    id
    workspaces {
      id
      title
      isShared
      ownerId
      todoLists {
        id
        isLocked
        title
        workspaceId
        todoItems {
          id
          title
          description
          cost
          isCompleted
        }
      }
    }
  }
}
query GetUsers {
  users {
    id
    workspaces {
      id
    }
  }
}

mutation CreateUser {
  createUser {
    id
  }
}

mutation CreateWorkspace($workspaceTitle: String!) {
  createWorkspace(title: $workspaceTitle) {
    id
    title
    isShared
    ownerId
    todoLists {
      id
      title
      isLocked
      workspaceId
      todoItems {
        id
        title
        description
        cost
        isCompleted
        todoListId
      }
    }
  }
}

mutation DeleteWorkspace($workspaceId: String!) {
  deleteWorkspace(id: $workspaceId) {
    id
  }
}

mutation UpdateWorkspace(
  $workspaceId: String!
  $workspaceIsShared: Boolean
  $workspaceTitle: String
) {
  updateWorkspace(
    id: $workspaceId
    isShared: $workspaceIsShared
    title: $workspaceTitle
  ) {
    id
    title
    isShared
  }
}

query GetTodoListById($todoListId: String!) {
  todoList(id: $todoListId) {
    id
    title
    isLocked
    workspaceId
    todoItems {
      id
      title
      description
      cost
      isCompleted
      todoListId
    }
  }
}

query GetWorkspaceById($id: String!) {
  getWorkspace(id: $id) {
    id
    title
    isShared
    ownerId
    todoLists {
      id
      title
      isLocked
      workspaceId
      todoItems {
        id
        description
        cost
        isCompleted
        title
      }
    }
  }
}

query GetTodoListsByWorkspace($workspaceId: String!) {
  todoLists(workspaceId: $workspaceId) {
    id
    title
    isLocked
  }
}

mutation CreateTodoList($todoListWorkspaceId: String!, $todoListTitle: String) {
  createTodoList(workspaceId: $todoListWorkspaceId, title: $todoListTitle) {
    id
    title
    isLocked
  }
}

subscription TodoListCreated($workspaceId: String!) {
  createTodoList(workspaceId: $workspaceId) {
    id
  }
}

mutation DeleteTodoList($todoListId: String!, $workspaceId: String!) {
  deleteTodoList(todoListId: $todoListId, workspaceId: $workspaceId) {
    id
  }
}

subscription TodoListDeleted($workspaceId: String!) {
  deleteTodoList(workspaceId: $workspaceId) {
    id
  }
}

mutation UpdateTodoList(
  $todoListId: String!
  $todoListIsLocked: Boolean
  $todoListTitle: String
) {
  updateTodoList(
    id: $todoListId
    isLocked: $todoListIsLocked
    title: $todoListTitle
  ) {
    id
    title
    isLocked
  }
}

subscription TodoListUpdated($id: String!) {
  updateTodoList(id: $id) {
    id
    title
    isLocked
    workspaceId
    todoItems {
      id
    }
  }
}

mutation CreateTodoItem(
  $todoItemTitle: String!
  $todoItemTodoListId: String!
  $todoItemDescription: String
  $todoItemCost: Int
) {
  createTodoItem(
    title: $todoItemTitle
    todoListId: $todoItemTodoListId
    description: $todoItemDescription
    cost: $todoItemCost
  ) {
    id
    title
    description
    cost
    isCompleted
  }
}

query GetTodoItemByIdQuery($id: String!) {
  todoItem(id: $id) {
    id
    title
    description
    cost
    isCompleted
  }
}

mutation DeleteTodoItem($todoItemId: String!, $todoListId: String!) {
  deleteTodoItem(id: $todoItemId, todoListId: $todoListId) {
    id
  }
}

subscription TodoItemDeleted($todoListId: String!) {
  deleteTodoItem(todoListId: $todoListId) {
    id
    title
    isLocked
    workspaceId
    todoItems {
      id
    }
  }
}

mutation UpdateTodoItem(
  $todoItemId: String!
  $todoItemIsCompleted: Boolean
  $todoItemTitle: String
  $todoItemDescription: String
  $todoItemCost: Int
) {
  updateTodoItem(
    id: $todoItemId
    isCompleted: $todoItemIsCompleted
    title: $todoItemTitle
    description: $todoItemDescription
    cost: $todoItemCost
  ) {
    id
    title
    description
    cost
    isCompleted
  }
}

subscription TodoItemUpdated($id: String!) {
  updateTodoItem(id: $id) {
    id
  }
}
